name: catedral
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.0.3+1 #MACOS
version: 1.0.4+10 #1.0.0+6 #Android

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  cloud_firestore: ^3.1.7
  #firebase_auth: ^3.3.6
  firebase_storage: ^10.2.7
  firebase_core: ^1.12.0
  provider: ^6.0.2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  carousel_slider: ^4.1.1
  url_launcher: ^6.0.20
  intl: ^0.17.0
  internet_connection_checker: ^0.0.1+3
  webview_flutter: ^3.0.4
  youtube_player_iframe: ^2.3.0
  dots_indicator: ^2.1.0
  connectivity_plus: ^2.3.8
  http: ^0.13.3
  sqflite: ^2.0.0
  rxdart: ^0.24.0
  easy_rich_text: ^0.2.2
  share: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#167d7f"
  android: true
  ios: true

flutter_icons:
  android: "ic_launcher"
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icon.png
     - assets/svg/
     - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
